name:                static-api-generator
version:             0.3.0.0
github:              jgalat/static-api-generator
license:             GPL
author:              Jorge Galat <jrgglt@gmail.com>
maintainer:          Jorge Galat <jrgglt@gmail.com>

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            A Haskell DSL for writing static APIs
category:            Network
stability:           experimental

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  A Haskell DSL for writing static APIs

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- data-default-class
- directory
- filepath
- text
- transformers

library:
  source-dirs: src

tests:
  static-api-generator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - directory
    - hspec
    - hspec-wai
    - static-api-generator
    - text
    - wai
    - wai-app-static